import type { Metadata } from 'next'
import Link from 'next/link'
import { BRAND, BRAND_RGB, FONT } from '@/lib/brand'

export const metadata: Metadata = {
  title: 'Terms of Service — Poursona',
  description: 'The terms that govern use of Poursona.',
}

const EFFECTIVE = 'May 20, 2026'

const SECTIONS: Array<{ h: string; body: string[] }> = [
  {
    h: '1. Agreement',
    body: [
      'These Terms of Service govern your access to and use of Poursona (the “Service”). By creating an account or using the Service, you agree to these terms. If you are using Poursona on behalf of a business, you represent that you are authorized to bind that business.',
    ],
  },
  {
    h: '2. The Service',
    body: [
      'Poursona provides an AI-powered guest recommendation experience for beverage venues, including catalog setup from your website, a branded QR guest chat, recommendations, order capture with staff notifications, and an analytics dashboard. Features may change over time.',
      'Recommendations are generated by an AI model and are provided for guidance only. You are responsible for the accuracy of your catalog and for confirming what is available to guests.',
    ],
  },
  {
    h: '3. Accounts and billing',
    body: [
      'Paid plans begin after any free trial and are billed monthly through Stripe. You can cancel anytime; cancellation stops future charges and pauses your guest experience. Fees are non-refundable except where required by law.',
    ],
  },
  {
    h: '4. Acceptable use',
    body: [
      'You agree not to misuse the Service, including by uploading unlawful content, attempting to disrupt or reverse-engineer the Service, or using it to violate the rights of others. You are responsible for complying with laws applicable to your venue, including those governing the responsible service of alcohol.',
    ],
  },
  {
    h: '5. Your content',
    body: [
      'You retain ownership of your catalog, branding, and other content you provide. You grant Poursona a license to use that content solely to operate and provide the Service to you and your guests.',
    ],
  },
  {
    h: '6. Availability and disclaimers',
    body: [
      'The Service is provided “as is.” We work to keep it reliable but do not guarantee uninterrupted or error-free operation, and we are not liable for the decisions guests make based on AI recommendations.',
    ],
  },
  {
    h: '7. Limitation of liability',
    body: [
      'To the maximum extent permitted by law, Poursona’s total liability for any claim relating to the Service is limited to the amount you paid us in the three months preceding the claim.',
    ],
  },
  {
    h: '8. Changes and termination',
    body: [
      'We may update these terms or the Service. We may suspend or terminate accounts that violate these terms. You may stop using the Service at any time.',
    ],
  },
  {
    h: '9. Contact',
    body: [
      'Questions about these terms? Email hello@pour-sona.com.',
    ],
  },
]

export default function TermsPage() {
  return (
    <div style={{ background: BRAND.darkBg, minHeight: '100vh', fontFamily: FONT.marketing, color: BRAND.textPrimary }}>
      <nav style={{ padding: '20px 40px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: `1px solid rgba(${BRAND_RGB.plum},.15)` }}>
        <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: 10, textDecoration: 'none' }}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/brand/logo-source.png" alt="Poursona" style={{ height: 36, width: 'auto', display: 'block' }} />
          <span style={{ fontFamily: FONT.brand, fontSize: 18, fontWeight: 700, letterSpacing: '.02em', color: BRAND.textPrimary }}>Poursona</span>
        </Link>
        <div style={{ display: 'flex', gap: 24, alignItems: 'center' }}>
          <Link href="/" style={{ color: BRAND.textSecondary, fontSize: 13, textDecoration: 'none', fontFamily: FONT.ui }}>Home</Link>
          <Link href="/pricing" style={{ color: BRAND.textSecondary, fontSize: 13, textDecoration: 'none', fontFamily: FONT.ui }}>Pricing</Link>
        </div>
      </nav>

      <main style={{ maxWidth: 720, margin: '0 auto', padding: '64px 24px 100px' }}>
        <h1 style={{ fontFamily: FONT.brand, fontSize: 'clamp(28px,5vw,40px)', fontWeight: 800, margin: '0 0 8px', letterSpacing: '-.02em' }}>Terms of Service</h1>
        <div style={{ color: BRAND.textMuted, fontSize: 13, marginBottom: 40, fontFamily: FONT.ui }}>Effective {EFFECTIVE}</div>

        {SECTIONS.map(s => (
          <section key={s.h} style={{ marginBottom: 28 }}>
            <h2 style={{ color: BRAND.copperAmber, fontSize: 18, fontWeight: 700, margin: '0 0 10px', fontFamily: FONT.brand }}>{s.h}</h2>
            {s.body.map((p, i) => (
              <p key={i} style={{ color: BRAND.textPrimary, fontSize: 15, lineHeight: 1.75, margin: '0 0 12px', fontFamily: FONT.marketing }}>{p}</p>
            ))}
          </section>
        ))}

        <p style={{ color: BRAND.textFaint, fontSize: 12, lineHeight: 1.7, marginTop: 40, borderTop: `1px solid rgba(${BRAND_RGB.plum},.15)`, paddingTop: 20, fontFamily: FONT.ui }}>
          This page is provided for transparency and is not legal advice. Have counsel review before relying on these terms commercially.
        </p>
      </main>

      <footer style={{ borderTop: `1px solid rgba(${BRAND_RGB.plum},.12)`, padding: '32px 40px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 16 }}>
        <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: 8, textDecoration: 'none' }}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/brand/logo-source.png" alt="Poursona" style={{ height: 26, width: 'auto', display: 'block' }} />
          <span style={{ fontFamily: FONT.brand, color: BRAND.textPrimary, fontWeight: 700, fontSize: 14 }}>Poursona</span>
        </Link>
        <div style={{ display: 'flex', gap: 24 }}>
          <Link href="/pricing" style={{ color: BRAND.textMuted, fontSize: 12, textDecoration: 'none', fontFamily: FONT.ui }}>Pricing</Link>
          <Link href="/privacy" style={{ color: BRAND.textMuted, fontSize: 12, textDecoration: 'none', fontFamily: FONT.ui }}>Privacy</Link>
          <a href="mailto:hello@pour-sona.com" style={{ color: BRAND.textMuted, fontSize: 12, textDecoration: 'none', fontFamily: FONT.ui }}>Contact</a>
        </div>
        <div style={{ color: BRAND.textMuted, fontSize: 12, fontFamily: FONT.ui }}>© 2026 Poursona</div>
      </footer>
    </div>
  )
}
